// src/components/VideoUploadProcessing.svelte
<script lang="ts">
    import { onMount, onDestroy } from "svelte";
    import { FaceMesh, type Results } from "@mediapipe/face_mesh";
    import { drawLandmarks } from "@mediapipe/drawing_utils";
    import {
      LEFT_IRIS_CENTER,
      RIGHT_IRIS_CENTER,
      LEFT_EYE_CORNER,
      RIGHT_EYE_CORNER,
      NOSE_TIP,
      getNormalizedIrisPosition,
      getLandmarks,
    } from "../scripts/utils";
  
    let video: HTMLVideoElement;
    let canvas: HTMLCanvasElement;
    let faceMesh: FaceMesh | null = null;
  
    let isPlaying = false;
    let videoLoaded = false;
    let key = 0;
  
    // Initialize FaceMesh whenever key changes.
    $: {
      key;
      if (canvas) {
        initFaceMesh();
      }
    }
  
    function initFaceMesh() {
      if (!canvas) return;
      const canvasCtx = canvas.getContext("2d");
      if (!canvasCtx) return;
  
      faceMesh = new FaceMesh({
        locateFile: (file: string) =>
          `https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/${file}`,
      });
  
      faceMesh.setOptions({
        maxNumFaces: 1,
        refineLandmarks: true,
        minDetectionConfidence: 0.43,
        minTrackingConfidence: 0.5,
      });
  
      faceMesh.onResults((results: Results) => {
        if (!canvasCtx) return;
        canvasCtx.save();
        canvasCtx.clearRect(0, 0, canvas.width, canvas.height);
        // Draw the image using the canvas's internal resolution.
        canvasCtx.drawImage(results.image, 0, 0, canvas.width, canvas.height);
        if (results.multiFaceLandmarks) {
          for (const landmarks of results.multiFaceLandmarks) {
            const irisCenterLandmarks = getLandmarks(landmarks, [
              LEFT_IRIS_CENTER,
              RIGHT_IRIS_CENTER,
            ]);
            drawLandmarks(canvasCtx, irisCenterLandmarks, {
              color: "#FF0000",
              lineWidth: 1,
            });
            const eyeCornerLandmarks = getLandmarks(landmarks, [
              LEFT_EYE_CORNER,
              RIGHT_EYE_CORNER,
            ]);
            drawLandmarks(canvasCtx, eyeCornerLandmarks, {
              color: "#FF0000",
              lineWidth: 1,
            });
            const noseLandmarks = getLandmarks(landmarks, [NOSE_TIP]);
            drawLandmarks(canvasCtx, noseLandmarks, {
              color: "#FF0000",
              lineWidth: 1,
            });
  
            const { normX, normY, timestamp } = getNormalizedIrisPosition(
              landmarks,
              canvas.width,
              canvas.height
            );
            console.log(
              `Normalized Iris Position: X: ${normX}, Y: ${normY}, Timestamp: ${timestamp}`
            );
          }
        }
        canvasCtx.restore();
      });
    }
  
    async function processVideo() {
      if (video && canvas && faceMesh) {
        async function onVideoFrame() {
          if (video.paused || video.ended) return;
          if (faceMesh) {
            await faceMesh.send({ image: video });
          }
          requestAnimationFrame(onVideoFrame);
        }
        requestAnimationFrame(onVideoFrame);
      }
    }
  
    function handleVideoUpload(event: Event) {
      const target = event.target as HTMLInputElement;
      const file = target.files?.[0];
      if (file && video) {
        video.src = URL.createObjectURL(file);
        video.onloadeddata = () => {
          videoLoaded = true;
          isPlaying = true;
          video.play();
          processVideo();
        };
      }
    }
  
    function handlePlay() {
      if (video) {
        isPlaying = true;
        video.play();
        processVideo();
      }
    }
  
    function handlePause() {
      if (video) {
        isPlaying = false;
        video.pause();
      }
    }
  
    function handleStop() {
      isPlaying = false;
      videoLoaded = false;
      key = key + 1;
      if (canvas) {
        const ctx = canvas.getContext("2d");
        if (ctx) {
          ctx.clearRect(0, 0, canvas.width, canvas.height);
        }
      }
    }
  
    onMount(() => {
      // Set the internal resolution to match the displayed size.
      if (canvas) {
        // Removing "px" when setting the canvas width/height attributes.
        canvas.width = Math.floor(window.innerWidth * 0.9);
        canvas.height = Math.floor(window.innerHeight * 0.9);
      }
    });
  
    onDestroy(() => {
      if (faceMesh) {
        faceMesh.close();
      }
    });
  </script>

  <div class="bg-base-200 m-4 overflow-hidden flex flex-col items-center justify-center border-primary rounded-lg border-4 opacity-90 shadow-glow h-[84svh]">
    <!-- Video file input -->
    <input
      type="file"
      accept="video/*"
      on:change={handleVideoUpload}
      class="flex p-2 bg-secondary text-secondary-content rounded-md w-fit mb-2 shadow-glow hover:scale-105 transition-transform"
    />
  
    <div class="border-2 border-accent rounded-lg">
      {#key key}
        <video bind:this={video} style="display: none;">
          <track kind="captions" />
        </video>
      {/key}
      <!-- The canvas is styled to use viewport units.
           It will always be 75vw by 75vh, following the browser window’s aspect ratio. -->
      <canvas
        bind:this={canvas}
        class="m-2 rounded bg-neutral shadow-glow"
        style="width: 75vw; height: 63vh;"
      ></canvas>
    </div>
  
    {#if videoLoaded}
      <div class="flex w-full font-semibold text-lg text-primary-content">
        <button
          on:click={handlePlay}
          disabled={isPlaying}
          class="bg-info m-2 ml-3 my-2 py-4 rounded-md w-full h-full text-info-content hover:bg-success hover:text-success-content hover:scale-105 hover:shadow-glow transition-transform"
          class:opacity-50={isPlaying}
          class:cursor-not-allowed={isPlaying}
        >
          Play
        </button>
        <button
          on:click={handlePause}
          disabled={!isPlaying}
          class="bg-warning m-2 py-4 rounded-md w-full h-full text-warning-content hover:bg-secondary hover:text-secondary-content hover:scale-105 hover:shadow-glow transition-transform"
          class:opacity-50={!isPlaying}
          class:cursor-not-allowed={!isPlaying}
        >
          Pause
        </button>
        <button
          on:click={handleStop}
          disabled={isPlaying}
          class="bg-accent m-2 mr-3 py-4 rounded-md w-full h-full text-accent-content hover:bg-error hover:text-error-content hover:scale-105 hover:shadow-glow-magenta transition-transform"
          class:opacity-50={isPlaying}
          class:cursor-not-allowed={isPlaying}
        >
          Stop
        </button>
      </div>
    {/if}
  </div>

// src/components/VideoUploadProcessing.tsx
import React, { useRef, useEffect, useState } from "react";
import { FaceMesh, type Results } from "@mediapipe/face_mesh";
import { drawLandmarks } from "@mediapipe/drawing_utils";
import {
  LEFT_IRIS_CENTER,
  RIGHT_IRIS_CENTER,
  LEFT_EYE_CORNER,
  RIGHT_EYE_CORNER,
  NOSE_TIP,
  getNormalizedIrisPosition,
  getLandmarks,
} from "../scripts/utils";

const VideoUploadProcessing: React.FC = () => {
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const faceMeshRef = useRef<FaceMesh | null>(null);
  const [isPlaying, setIsPlaying] = useState(false);
  const [videoLoaded, setVideoLoaded] = useState(false);
  const [key, setKey] = useState(0);

  useEffect(() => {
    const canvasElement = canvasRef.current;
    const canvasCtx = canvasElement?.getContext("2d") ?? null;

    if (canvasElement && canvasCtx) {
      faceMeshRef.current = new FaceMesh({
        locateFile: (file) =>
          `https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/${file}`,
      });

      faceMeshRef.current.setOptions({
        maxNumFaces: 1,
        refineLandmarks: true,
        minDetectionConfidence: 0.43,
        minTrackingConfidence: 0.5,
      });

      faceMeshRef.current.onResults((results: Results) => {
        if (!canvasCtx) return;
        canvasCtx.save();
        canvasCtx.clearRect(0, 0, canvasElement.width, canvasElement.height);
        canvasCtx.drawImage(
          results.image,
          0,
          0,
          canvasElement.width,
          canvasElement.height
        );
        if (results.multiFaceLandmarks) {
          for (const landmarks of results.multiFaceLandmarks) {
            const irisCenterLandmarks = getLandmarks(landmarks, [
              LEFT_IRIS_CENTER,
              RIGHT_IRIS_CENTER,
            ]);
            drawLandmarks(canvasCtx, irisCenterLandmarks, {
              color: "#FF0000",
              lineWidth: 1,
            });
            const eyeCornerLandmarks = getLandmarks(landmarks, [
              LEFT_EYE_CORNER,
              RIGHT_EYE_CORNER,
            ]);
            drawLandmarks(canvasCtx, eyeCornerLandmarks, {
              color: "#FF0000",
              lineWidth: 1,
            });
            const noseLandmarks = getLandmarks(landmarks, [NOSE_TIP]);
            drawLandmarks(canvasCtx, noseLandmarks, {
              color: "#FF0000",
              lineWidth: 1,
            });

            const { normX, normY, timestamp } = getNormalizedIrisPosition(
              landmarks,
              canvasElement.width,
              canvasElement.height
            );
            console.log(
              `Normalized Iris Position: X: ${normX}, Y: ${normY}, Timestamp: ${timestamp}`
            );
          }
        }
        canvasCtx.restore();
      });
    }
  }, [key]);

  const handleVideoUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file && videoRef.current) {
      const videoElement = videoRef.current;
      videoElement.src = URL.createObjectURL(file);
      videoElement.onloadeddata = () => {
        setVideoLoaded(true);
        setIsPlaying(true);
        videoElement.play();
        processVideo();
      };
    }
  };

  const processVideo = () => {
    const videoElement = videoRef.current;
    const canvasElement = canvasRef.current;
    if (videoElement && canvasElement && faceMeshRef.current) {
      const onVideoFrame = async () => {
        if (!videoElement.paused && !videoElement.ended) {
          await faceMeshRef.current!.send({ image: videoElement });
          requestAnimationFrame(onVideoFrame);
        }
      };
      requestAnimationFrame(onVideoFrame);
    }
  };

  const handlePlay = () => {
    if (videoRef.current) {
      setIsPlaying(true);
      videoRef.current.play();
      processVideo();
    }
  };

  const handlePause = () => {
    if (videoRef.current) {
      setIsPlaying(false);
      videoRef.current.pause();
    }
  };

  const handleStop = () => {
    setIsPlaying(false);
    setVideoLoaded(false);
    setKey((prevKey) => prevKey + 1);
    const canvasElement = canvasRef.current;
    const canvasCtx = canvasElement?.getContext("2d") ?? null;
    if (canvasCtx) {
      canvasCtx.clearRect(0, 0, canvasElement!.width, canvasElement!.height);
    }
  };

  return (
    <div className="flex flex-col items-center justify-center border-accent-magenta rounded-lg border-2 opacity-90 shadow-glow bg-base-light dark:bg-base">
      <input
        type="file"
        accept="video/*"
        onChange={handleVideoUpload}
        className="flex text-white dark:text-gray-300 p-2 bg-gradient-to-b from-accent-magenta to-accent-green rounded-md w-fit my-2 shadow-glow hover:scale-105 transition-transform"
      />
      <div className="border-b-2 border-accent-magenta">
        <video
          key={key}
          ref={videoRef}
          width="640"
          height="480"
          style={{ display: "none" }}
        ></video>
        <canvas
          ref={canvasRef}
          width="640"
          height="480"
          className="m-2 rounded bg-gradient-to-r from-accent-cyan via-accent-magenta to-accent-green shadow-glow"
        ></canvas>
      </div>
      {videoLoaded && (
        <div className="flex w-full font-semibold text-lg text-white dark:text-gray-300">
          <button
            onClick={handlePlay}
            disabled={isPlaying}
            className={`bg-accent-cyan m-2 ml-3 my-2 py-4 rounded-md w-full h-full text-black dark:text-white 
                    hover:bg-accent-green hover:scale-105 hover:shadow-glow transition-transform ${
                      isPlaying ? "opacity-50 cursor-not-allowed" : ""
                    }`}
          >
            Play
          </button>
          <button
            onClick={handlePause}
            disabled={!isPlaying}
            className={`bg-accent-yellow m-2 py-4 rounded-md w-full h-full text-black dark:text-white 
                    hover:bg-accent-orange hover:scale-105 hover:shadow-glow transition-transform ${
                      !isPlaying ? "opacity-50 cursor-not-allowed" : ""
                    }`}
          >
            Pause
          </button>
          <button
            onClick={handleStop}
            disabled={isPlaying}
            className={`bg-accent-magenta m-2 mr-3 py-4 rounded-md w-full h-full text-black dark:text-white 
                    hover:bg-accent-red hover:scale-105 hover:shadow-glow-magenta transition-transform ${
                      isPlaying ? "opacity-50 cursor-not-allowed" : ""
                    }`}
          >
            Stop
          </button>
        </div>
      )}
    </div>
  );
};

export default VideoUploadProcessing;
